
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], weight: ["400", "500", "600"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-white flex flex-col justify-center w-full h-[100vh] items-center`}
      >
        {children}
        <footer className="absolute bottom-[43px] text-[#71717A]">Powered by <span className="font-bold text-black">X</span></footer>
      </body>
    </html>
  );
}
